# LIST OF FOUR ELEMENTS

In [30]:
x=([5,6,7,8])

In [31]:
print(type(x))

<class 'list'>


In [32]:
print(len(x))

4


# CJ AND KFC LIST

In [94]:
CJ=([9.99,7.99,7.49,7.400,6.29,4.99])

In [95]:
KFC=([7.5,5,4.4,3.75,2.25])

In [101]:
print(CJ+KFC)

[9.99, 7.99, 7.49, 7.4, 6.29, 4.99, 7.5, 5, 4.4, 3.75, 2.25]


In [138]:
print(CJ)-(KFC)

[9.99, 7.99, 7.49, 7.4, 6.29, 4.99]


TypeError: unsupported operand type(s) for -: 'NoneType' and 'list'

In [ ]:
print(type(CJ))

<class 'list'>


In [ ]:
print(len(CJ))

6


In [ ]:
print(type(KFC))

<class 'list'>


In [ ]:
print(len(KFC))

5


# CREATING ARRAYS

In [ ]:
import numpy as np

In [63]:
CJ=([9.99,7.99,7.49,7.400,6.29])

In [64]:
KFC=([7.5,5,4.4,3.75,2.25])

In [65]:
CJ_array=np.array(CJ)
CJ_array

array([9.99, 7.99, 7.49, 7.4 , 6.29])

In [66]:
KFC_array=np.array(KFC)
KFC_array


array([7.5 , 5.  , 4.4 , 3.75, 2.25])

In [67]:
CJ_array.dtype

dtype('float64')

In [74]:
KFC_array.dtype

dtype('float64')

In [75]:
(CJ_array-KFC_array)

array([2.49, 2.99, 3.09, 3.65, 4.04])

In [86]:
np.mean(CJ_array-KFC_array)

3.2520000000000002

In [87]:
np.std(CJ_array)

1.2135303869289802

In [88]:
np.std(KFC_array)

1.7235428628264513

In [89]:
np.std(CJ_array-KFC_array)

0.5394219127918332